config/routes.rb
Rails.application.routes.draw do
  get 'band/top'
  get 'band/new'
  post 'bands' => 'band#create'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get '/profile/:id' => 'users#show', as: 'user_show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/band_controller.rb
class BandController < ApplicationController
  def top
    @band = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    @band.save
    redirect_to band_top_path, notice: 'バンドを登録しました'
  end

  private

  def band_params
      params.require(:band).permit(:name, :member, :genre, :introduction)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]
  before_action :set_user, only: [:show, :edit]

  def show
  end

  def edit
  end


  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/band/new.html.erb
<h1>バンド登録</h1>

<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @band.errors.count %>件のエラー:</h2>

      <ul>
        <% @band.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  バンド名
  <%= f.text_field :name, { class: "form-control title-field" } %>

  メンバー
  <%= f.text_field :member, { class: "form-control title-field" } %>

  主なジャンル
  <%= f.text_field :genre, { class: "form-control title-field" } %>

  紹介
  <%= f.text_area :introduction, { class: "form-control content-field" } %>
  <%= f.submit "登録", { class: "btn primary-btn" } %>
<% end %>

app/views/band/top.html.erb
<h1>登録バンド一覧</h1>
<%= link_to "バンドを新規登録", band_new_path %>

<% @band.each do |band| %>
  <h3><%= band.name %></h3>
<% end %>

app/views/home/top.html.erb
<h1>バンド調整システム（仮名）</h1>
<p>普段開発まったくやらない人が勉強がてら作ってるので大目に見てください(笑)</p>
<p>Bajust　→　Band ajust system.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bajust</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar">
      <div class="container">
        <div id="logo"><%= link_to "Bajust", root_path %></div>
        <% if user_signed_in? %>
          <ul class="header-right">
            <li><%= link_to "プロフィール", user_show_path(id: current_user.id) %></li>
            <li><%= link_to "バンド", band_top_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="header-right">
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </header>

    <div class="container">
      <p class="alert alert-success"><%= notice %></p>
      <p class="alert alert-danger"><%= alert %></p>
    <%= yield %>
  </dev>

    <div class="container">
      <footer class="footer">
        <div class="small">
          &copy; 2017 SideLovers.
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/users/edit.html.erb
<h1>登録情報の変更</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  ニックネーム
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス（変更不可）
  <%= @user.email %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/show.html.erb
<h1>プロフィール</h1>

<%= link_to "編集", '/users/edit' %>

<h3>ニックネーム</h3>
<p><%= @user.name %></p>

<h3>メールアドレス</h3>
<p><%= @user.email %></p>